# general settings
name: test_DiffIRS2_0.0008
model_type: DiffIRS2Model
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0


# dataset and data loader settings
datasets:
  # Uncomment these for validation
  val_1:
    name: DOTA
    type: DeblurPairedDataset
    dataroot_gt: ./../../ELIC_Grad_Guide/results/ELIC_arch_Test_GT_GEN/mse_0.0008
    dataroot_lq: ./../../ELIC_Grad_Guide/results/ELIC_arch_Test_LQ_GEN/mse_0.0008
    io_backend:
      type: disk

# network structures
network_g:
  type: DiffIRS2
  n_encoder_res: 5
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2, 2, 4, 4] #[3,5,6,6]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2
  bias: False
  LayerNorm_type: WithBias
  n_denoise_res: 8 #1
  linear_start: 0.1
  linear_end: 0.99
  timesteps: 4 #4

# network structures
network_S1:
  type: DiffIRS1
  n_encoder_res: 5
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2, 2, 4, 4]  #[3,5,6,6]
  num_refinement_blocks: 2
  heads: [1,2,4,8]
  ffn_expansion_factor: 2
  bias: False
  LayerNorm_type: WithBias
  group: 4

# path
path:
  # use the pre-trained Real-ESRNet model
  pretrain_network_g: experiments/pre_trained/mlkk_0.0008_GP4_S2/net_g_latest.pth   #net_g_288000.pth === 27.3731 PSNR
#  pretrain_network_g: experiments/pre_trained/DM_Step/mlkk_0.0008_GP4_T4/net_g_latest.pth   # 测试 step T 消融
  pretrain_network_S1: experiments/pre_trained/mlkk_0.0008_GP4_S1/net_g_latest.pth  # 28.5742 PSNR
  param_key_g: params_ema
  strict_load_g: False
  ignore_resume_networks: network_S1



# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.5

  encoder_iter: 100000
  total_iter: 400000
  lr_encoder: !!float 2e-4
  lr_sr: !!float 2e-4
  gamma_encoder: 0.1
  gamma_sr: 0.5
  lr_decay_encoder: 60000
  lr_decay_sr: 80000
  warmup_iter: -1  # no warm up

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  kd_opt:
    type: KDLoss
    loss_weight: 1
    temperature: 0.15


val:
  save_img: True
  suffix: ~  # add suffix to saved images, if None, use exp name

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: False

  # logging settings
logger:
  print_freq: 20 #1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~



