# general settings
name: train_DiffIRS2_0.0004_T4 #_EN
model_type: DiffIRS2Model
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: DeblurPairedDataset
    dataroot_gt: ./../../ELIC_Grad_Guide/results/ELIC_arch_Train_GT_GEN/mse_0.0004
    dataroot_lq: ./../../ELIC_Grad_Guide/results/ELIC_arch_Train_LQ_GEN/mse_0.0004
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk


    num_worker_per_gpu: 12
    batch_size_per_gpu: 2
    mini_batch_sizes: [2]             # Batch size per gpu
    iters: [150000]
    gt_size: 256   # Max patch size for progressive training
    gt_sizes: [256]  # Patch sizes for progressive training.

    # data loader
    use_shuffle: true
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: ValSet
    type: DeblurPairedDataset
    dataroot_gt: ./../../ELIC_Grad_Guide/results/ELIC_arch_Test_GT_GEN/mse_0.0008
    dataroot_lq: ./../../ELIC_Grad_Guide/results/ELIC_arch_Test_LQ_GEN/mse_0.0004
    io_backend:
      type: disk

# network structures
network_g:
  type: DiffIRS2
  n_encoder_res: 5
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2, 2, 4, 4] #[3,5,6,6]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2
  bias: False
  LayerNorm_type: WithBias
  n_denoise_res: 8 #1
  linear_start: 0.1
  linear_end: 0.99
  timesteps: 4 #16 #4

# network structures
network_S1:
  type: DiffIRS1
  n_encoder_res: 5
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2, 2, 4, 4]  #[3,5,6,6]
  num_refinement_blocks: 2
  heads: [1,2,4,8]
  ffn_expansion_factor: 2
  bias: False
  LayerNorm_type: WithBias
  group: 4


# path
path:
  pretrain_network_g: experiments/pre_trained/mlkk_0.0004_GP4_S2/net_g_latest.pth   #net_g_288000.pth === 27.3731 PSNR
#  pretrain_network_g: experiments/pre_trained/mlkk_0.0004_GP4_EN_S2/net_g_192000.pth
  pretrain_network_S1: experiments/pre_trained/mlkk_0.0004_GP4/net_g_288000.pth  # 28.5742 PSNR
  param_key_g: params_ema
  strict_load_g: False
  resume_state: ~
  ignore_resume_networks: network_S1

# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.5

  encoder_iter: 200000 # default 100000
  total_iter: 400000
  lr_encoder: !!float 1e-4
  lr_sr: !!float 1e-4
  gamma_encoder: 0.1
  gamma_sr: 0.5
  lr_decay_encoder: 60000
  lr_decay_sr: 80000
  warmup_iter: -1  # no warm up

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  kd_opt:
    type: KDLoss
    loss_weight: 1
    temperature: 0.15

# Uncomment these for validation
# validation settings
val:
  window_size: 8
  val_freq: !!float 500 #5e3
  save_img: False

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20 #1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
